name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        
      - name: Déployer sur DigitalOcean
        run: |
            ssh -o StrictHostKeyChecking=no root@206.81.16.150 -i C:\Users\p-gar\xen<< 'EOF'
            cd /root/home/deployer
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF
