name: Deploy FastAPI to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        
      - name: Déployer sur DigitalOcean
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} -i /Users/p-gar/xen<< 'EOF'
            cd /root/home/deployer
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF
