name: Setup Python on DigitalOcean Droplet

on:
  push:
    branches:
      - main  # Exécute le workflow à chaque push sur main

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
      # ✅ Étape 1 : Récupérer le code depuis GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Étape 2 : Configurer la clé SSH
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      # ✅ Étape 3 : Vérifier la connexion SSH
      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} "echo '✅ SSH connection successful'"

      # ✅ Étape 4 : Installer Python sur le Droplet
      - name: Install Python
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
          # Mettre à jour le système
          sudo apt update && sudo apt upgrade -y

          # Installer Python, pip et venv
          sudo apt install -y python3 python3-pip python3-venv

          # Vérifier l'installation
          python3 --version
          pip3 --version
        EOF
